-- Contextual verification and driver payouts.
-- Applied once by Migrate through schema_migrations. PostgreSQL remains the
-- lifecycle and financial source of truth; browser storage is never used here.

-- A receipt can only ever support one payment submission. The service also
-- verifies customer ownership, kind and Pending status before insertion. Keep
-- historical payment rows when a legacy import reused a receipt; the newest
-- row retains the link and old rows remain auditable without a receipt pointer.
UPDATE payments p SET receipt_doc = NULL
WHERE receipt_doc IS NOT NULL AND EXISTS (
  SELECT 1 FROM payments newer
  WHERE newer.receipt_doc = p.receipt_doc AND newer.id > p.id
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_payments_receipt_doc_once
  ON payments(receipt_doc) WHERE receipt_doc IS NOT NULL;

-- Driver payout account secrets are AES-256-GCM envelopes generated by the
-- application.  Only display_last4 and method are safe to return in lists.
CREATE TABLE IF NOT EXISTS driver_payout_accounts (
  driver_id BIGINT PRIMARY KEY REFERENCES drivers(id) ON DELETE CASCADE,
  method TEXT NOT NULL CHECK (method IN ('Bank account / IBAN', 'JazzCash', 'Easypaisa')),
  account_title_enc TEXT NOT NULL,
  account_number_enc TEXT,
  iban_enc TEXT,
  phone_enc TEXT,
  display_last4 TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One completed booking item can be paid to its assigned driver at most once.
-- account_enc stores the encrypted destination snapshot used for that payout;
-- reference/note are the operator audit details.
CREATE TABLE IF NOT EXISTS driver_payouts (
  id BIGSERIAL PRIMARY KEY,
  booking_id TEXT NOT NULL REFERENCES bookings(id) ON DELETE RESTRICT,
  booking_item_pos INT NOT NULL,
  driver_id BIGINT NOT NULL REFERENCES drivers(id) ON DELETE RESTRICT,
  amount BIGINT NOT NULL CHECK (amount > 0),
  method TEXT NOT NULL,
  account_enc TEXT NOT NULL,
  account_display TEXT NOT NULL DEFAULT '',
  reference TEXT NOT NULL,
  note TEXT,
  paid_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (booking_id, booking_item_pos)
);
CREATE INDEX IF NOT EXISTS idx_driver_payouts_driver ON driver_payouts(driver_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_driver_payouts_booking ON driver_payouts(booking_id, booking_item_pos);
